const Users = [
  {
    id: "1",
    name: "Rafay",
    bio: "Food enthusiast and travel lover. Always looking for the next great meal!",
    postsCount: 48,
    followersCount: 321,
    followingCount: 342,
    isFollowing: false,
  },
  {
    id: "321",
    name: 321,
    bio: "Food enthusiast and travel lover. Always looking for the next great meal!",
    postsCount: 48,
    followersCount: 1254,
    followingCount: 342,
    isFollowing: false,
  },
  {
    id: "use32r123",
    name: "use32r123",
    bio: "Food enthusiast and travel lover. Always looking for the next great meal!",
    postsCount: 48,
    followersCount: 1254,
    followingCount: 342,
    isFollowing: false,
  },
  {
    id: "user1123",
    name: "user1123",
    bio: "Food enthusiast and travel lover. Always looking for the next great meal!",
    postsCount: 48,
    followersCount: 1254,
    followingCount: 342,
    isFollowing: false,
  },
  {
    id: "user3123",
    name: "user3123",
    bio: "Food enthusiast and travel lover. Always looking for the next great meal!",
    postsCount: 48,
    followersCount: 1254,
    followingCount: 342,
    isFollowing: false,
  },
];
